%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\matlab\ymaps_code\2023-10-04_16-08-34.txt
%
% Auto-generated by MATLAB on 04-Oct-2023 22:32:19

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["eeg1", "eeg2", "eeg3", "eeg4", "eeg5", "eeg6", "eeg7"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
trial7 = readtable("D:\matlab\ymaps_code\2023-10-04_16-08-34.txt", opts);


%% Clear temporary variables
clear opts